collections:
  releases:
    output: true

repository: 503meditation.github.io/helloworld

url: https://gurumeditation.zone

include:
 - CNAME

exclude:
 - README.md
 - Gemfile
 - Gemfile.lock
 - publish
 - fullpublish

# baseurl: /helloworld

defaults:
  - scope:
      path: ""
      type: "releases"
    values:
      layout: "releases"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
