collections:
  sounds:
    output: true

repository: 503meditation.github.io/helloworld

url: https://gurumeditation.zone

# include:
#  - "CNAME"
#  - "favicon.jpeg"

exclude:
 - "README.md"
 - "Gemfile"
 - "Gemfile.lock"
 - "publish"
 - "fullpublish"
 - ".DS_Store"

# baseurl: /helloworld

defaults:
  - scope:
      path: ""
      type: "sounds"
    values:
      layout: "sounds"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
